app = "gardenbred"         # đổi thành tên app bạn muốn
primary_region = "sin"     # hoặc region bạn chọn

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3000"
  DB_PATH = "/data/game.db"

[[mounts]]
  source = "data"
  destination = "/data"

[[services]]
  protocol = "tcp"
  internal_port = 3000

  [services.concurrency]
    type = "connections"
    soft_limit = 80
    hard_limit = 100

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls","http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
